### ISSUE TITLE
[1.21] Neoforge crashed with AE2 and Solr Flux Reborn latest version

### ISSUE THREAD

**Issue by Periam** [dragon-forge/SolarFluxReborn#31] opened 2024-07-17 13:19 UTC
After installing the latest version of the mods and their dependencies the game crash:

Neoforge 21.0.98
appliedenergistics2-19.0.12-alpha.jar
HammerLib-1.21-21.0.13.jar
jei-1.21-neoforge-19.5.0.35.jar
SolarFluxReborn-1.21-21.0.1.jar

[crash-2024-07-17_10.11.26-fml.txt](https://github.com/user-attachments/files/16266172/crash-2024-07-17_10.11.26-fml.txt)
[debug.log](https://github.com/user-attachments/files/16266175/debug.log)
[latest.log](https://github.com/user-attachments/files/16266177/latest.log)

![image](https://github.com/user-attachments/assets/376620f3-a46e-4e78-9233-bb3d65199ade)

**Comment by Zeitheron** [comment] 2024-08-07 06:35
Duplicate of #32

**Closed as completed by Zeitheron** 2024-08-07 06:35 UTC
