### ISSUE TITLE
[1.19.2] Mod causes crashes even if worked fine yesterday

### ISSUE THREAD

**Issue by SoulOfSorin** [dragon-forge/SolarFluxReborn#9] opened 2023-06-23 10:13 UTC
The title may be strange but let me explain : I played Minecraft two days ago, with Solar Flux Reborn all working fine, no problem.
But since yesterday i can't launch the game, it crashes with this error :

The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class org.zeith.solarflux.init.ItemsSF

Here is a full crashlog : 

https://pastebin.com/5js0vkWM

**Comment by Zeitheron** [comment] 2023-06-23 10:18
This means that another mod is breaking the game, and by extent, causing this issue to SFR.
Will need full game log file to be able to tell exactly what has cause this.

**Comment by SoulOfSorin** [comment] 2023-06-23 10:35
Okay, by having ANOTHER error (not SFR related) i deleted **Create Central Kitchen** which "_failed to load correctly_" (whatever this could mean) i discovered that it was causing the issue. 
So yeah, sorry for bothering you.
I could make it crash again to have a fresh log, but i'm guessing you have better things to do that analyzing a problem caused by another mod.
Have a great day.

**Comment by Zeitheron** [comment] 2023-06-23 10:41
You can just send the logs, they will have the same mod crashing, just that now is it blaming another mod.

This is a very common forge problem (since 1.13, and still hasn't been addressed... Why? Idunno)

Basically, when a mod fails, it breaks forge event bus system, and registry-related stuff.

Then, it (for no real reason) continues to load mods, as if nothing happened, to only then stumble across a mod that uses that registration stuff / event bus, and causes that mod to crash too, which is then interpreted as a hard crash, and is what you see in crash logs.

Always need to check the logs to see a mod soft-crashing... Dumb forge system.

**Comment by SoulOfSorin** [comment] 2023-06-23 10:48
Oooooh thanks for the explanations, i had so many problems like that during the precedents weeks, and i just tossed the problematic mods away because googling the problem wasn't helpful.
So you need a latest.log ? Of a working Minecraft or a crashing one ?

**Comment by Zeitheron** [comment] 2023-06-23 10:51
Need a latest log of crashing instance..Those logs contain the soft crashing mod

**Comment by SoulOfSorin** [comment] 2023-06-23 10:56
Here it comes a fresh latest.log

https://pastebin.com/7p4fKB8B

I can't make a pastebin of debug.log (too heavy) but i could upload it if needed.

**Comment by Zeitheron** [comment] 2023-06-23 11:11
Yep, your assumptions were spot on! But the mod itself is not really broken.
Here's the thing, 
The initial issue with the mod is `Failed to create mod instance. ModID: create_central_kitchen, class plus.dragons.createcentralkitchen.CentralKitchen
java.lang.reflect.InvocationTargetException: null`

Which might say as much as "Oh well, it's broken, gotta remove it now"


When in reality, the issue lies in config file. If we scroll past the first stack trace, we find `Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[pieOverhaulBlackList]" defined twice in its table.`

TOML is the new config standard for mods enforced by forge.
And so, the issue seems to be that the mod's config file has duplicate pieOverhaulBlackList list defined. I would suggest resetting the mod's config file and try again with it installed!

**Comment by SoulOfSorin** [comment] 2023-06-23 11:32
It works !
But if i understand correctly, that means that because i played with a mod in another Minecraft version, and that mod has a .toml config file, playing a newer version of the game with the very same mod might cause heavy issues because Forge ... duplicates config rules within the same file ? That's completely stupid.
And it brings another stupid thing : Why when googling this problem, this solution is not in the results ? It's simple and efficient. 
I'm very grateful for your insights, it will save me a lot of time, frustration and paracetamol.

**Comment by Zeitheron** [comment] 2023-06-23 11:34
You're welcome! I was considering writing a tool to figure out the potential cause of such crashes (using logs ofc) as the forge has become increasingly annoying in a lot of ways. This is just one of them all. And no one at forge seems to care enough about it, considering this has been relevant since 1.13, and all the way up to 1.20.1 (and I would imagine it won't be solved anytime soon...)

**Comment by Zeitheron** [comment] 2023-06-23 11:45
I'm closing this issue as we have figured out it's origin and fixed it.

**Closed as not planned by Zeitheron** 2023-06-23 11:45 UTC
